Sat 16 Sep 2017 23:31:22, operations.py ,event_name : news_list_request,user_id : gg@qq.com,user_ip : ::1
Sat 16 Sep 2017 23:32:52, operations.py ,event_name : news_list_request,user_id : gg@qq.com,user_ip : ::1
Sat 16 Sep 2017 23:33:16, operations.py,event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:33:56, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:34:13, operations.py, event_name : news_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:35:42, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:35:45, operations.py, event_name : news_request, user_id : gg@qq.com, user_ip : ::1, news_id : 4DOKIiAWTFJnuIUgsfMbFg==

Sat 16 Sep 2017 23:37:43, operations.py, event_name : news_request, user_id : gg@qq.com, user_ip : ::1, news_id : 4DOKIiAWTFJnuIUgsfMbFg==

Sat 16 Sep 2017 23:44:29, base_connection.pyRead empty data, calling disconnect
Sat 16 Sep 2017 23:44:29, base_connection.pySocket closed when connection was open
Sat 16 Sep 2017 23:44:29, connection.pyDisconnected from RabbitMQ at donkey.rmq.cloudamqp.com:5672 (0): Not specified
Sat 16 Sep 2017 23:44:29, blocking_connection.pyConnection close detected
Sat 16 Sep 2017 23:44:29, rpclib.pyJsonRpcError(-32603): Internal JSON-RPC error. -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 26, in logNewsClickForUser
    return operations.logNewsClickForUser(user_id, news_id, user_ip)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/operations.py", line 102, in logNewsClickForUser
    cloudAMQP_client.sendMessage(message)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/../common/cloudAMQP_client.py", line 24, in sendMessage
    queue = self.channel.queue_declare(self.queue_name)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Sat 16 Sep 2017 23:46:01, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:46:16, rpclib.pyJsonRpcError(-32603): 'NoneType' object has no attribute 'send' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 26, in logNewsClickForUser
    return operations.logNewsClickForUser(user_id, news_id, user_ip)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/operations.py", line 102, in logNewsClickForUser
    cloudAMQP_client.sendMessage(message)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/../common/cloudAMQP_client.py", line 22, in sendMessage
    body=json.dumps(message))
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2064, in publish
    immediate=immediate)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'

Sat 16 Sep 2017 23:48:16, rpclib.pyJsonRpcError(-32603): 'NoneType' object has no attribute 'send' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 26, in logNewsClickForUser
    return operations.logNewsClickForUser(user_id, news_id, user_ip)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/operations.py", line 102, in logNewsClickForUser
    cloudAMQP_client.sendMessage(message)
  File "/home/yuyu/bittigercs503-1703-llliuyu/week10/backend_server/../common/cloudAMQP_client.py", line 22, in sendMessage
    body=json.dumps(message))
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2064, in publish
    immediate=immediate)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/home/yuyu/.local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'

Sat 16 Sep 2017 23:48:44, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 16 Sep 2017 23:48:48, operations.py, event_name : news_request, user_id : gg@qq.com, user_ip : ::1, news_id : TT1VqI5I+rL6HutEk4t87A==

Sat 16 Sep 2017 23:49:04, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:12:22, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:26:43, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:27:23, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:27:23, rpclib.pyJsonRpcError(-32603): 'datetime.timedelta' object has no attribute 'microsecond' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 24, in getNewsSummariesForUser
    print (endtime - starttime).microsecond
AttributeError: 'datetime.timedelta' object has no attribute 'microsecond'

Sun 17 Sep 2017 11:27:40, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:27:40, rpclib.pyJsonRpcError(-32603): 'datetime.timedelta' object has no attribute 'microsecond' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 24, in getNewsSummariesForUser
    print (endtime - starttime).microsecond
AttributeError: 'datetime.timedelta' object has no attribute 'microsecond'

Sun 17 Sep 2017 11:31:15, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:31:15, rpclib.pyJsonRpcError(-32603): 'datetime.timedelta' object has no attribute 'microsecond' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    print c.microsecond
AttributeError: 'datetime.timedelta' object has no attribute 'microsecond'

Sun 17 Sep 2017 11:31:27, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:31:27, rpclib.pyJsonRpcError(-32603): 'datetime.timedelta' object has no attribute 'microsecond' -- Traceback (most recent call last):
  File "/home/yuyu/.local/lib/python2.7/site-packages/pyjsonrpc/rpclib.py", line 114, in call
    result = rpc_function(*positional_params, **named_params)
  File "service.py", line 25, in getNewsSummariesForUser
    print c.microsecond
AttributeError: 'datetime.timedelta' object has no attribute 'microsecond'

Sun 17 Sep 2017 11:33:00, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:36:12, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:36:26, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 11:37:16, operations.py, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:15, operations.py, event_name : news_request, user_id : gg@qq.com, user_ip : ::1, news_id : li2AX2DPp8QMeshsDDYCgQ==

Sun 17 Sep 2017 19:54:19, service.pyoperations.getNewsSummariesForUser, 53 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:31, service.pyoperations.getNewsSummariesForUser, 15 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:33, service.pyoperations.getNewsSummariesForUser, 18 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:35, service.pyoperations.getNewsSummariesForUser, 16 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:38, service.pyoperations.getNewsSummariesForUser, 16 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:40, service.pyoperations.getNewsSummariesForUser, 16 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:42, service.pyoperations.getNewsSummariesForUser, 14 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sun 17 Sep 2017 19:54:44, service.pyoperations.getNewsSummariesForUser, 19 ms, event_name : news_list_request, user_id : gg@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:10:15, operations.py, event_name : news_request, user_id : qq@qq.com, user_ip : ::1, news_id : gF8acXIiZOL98S6qpBOBxw==

Sat 23 Sep 2017 13:10:27, service.pyoperations.getNewsSummariesForUser, 50 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:10:30, service.pyoperations.getNewsSummariesForUser, 15 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:10:32, service.pyoperations.getNewsSummariesForUser, 16 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:10:38, service.pyoperations.getNewsSummariesForUser, 18 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:11:19, service.pyoperations.getNewsSummariesForUser, 15 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:12:00, service.pyoperations.getNewsSummariesForUser, 43 ms, event_name : news_list_request, user_id : qq@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:15:25, operations.py, event_name : news_request, user_id : qq@qq.com, user_ip : ::1, news_id : lJLtCceI90bwjjHUcoLiqw==

Sat 23 Sep 2017 13:16:45, service.pyoperations.getNewsSummariesForUser, 43 ms, event_name : news_list_request, user_id : tt@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:17:57, service.pyoperations.getNewsSummariesForUser, 44 ms, event_name : news_list_request, user_id : tt@qq.com, user_ip : ::1
Sat 23 Sep 2017 13:18:03, service.pyoperations.getNewsSummariesForUser, 14 ms, event_name : news_list_request, user_id : tt@qq.com, user_ip : ::1
